sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        AjKjKQyggwYi+0Vo4ImVkjbsxk02vhrA4EbBjA3cdectBrAFw6enZWw2cClgCah1BNzpwmCWQgOEUP1Zb8H++aypovHWg3N0aq2f5i9HrWjKb9Eq+Ho6ORBlWYi+Bdefu+6GCAvutPwUbWJhMB4IR6cZYszErRZeix1PJ4JDfJ8+6q1zKKqnw3hh0LolAqtqeBqI0OxHTL2dM/0Kx+iewzZjQiN9l33JS6jc7voTdbMogn0nk/mX7T5s3vOow35T+7VfV9EQ1JaMKCQZEQF0J0ZsRUurqXJCGOOAdR/83y6ljoLZuQIyGDm2udC44Nu0HwJSkKU+2i6t3viy5qJoDUAbEaR04k9Y2mFPkUW61zjSJd94X+u+EmevNXCiNNlbv9/+kW811EQjultpEA2RhfsajFDVrEphyuXZZemVOC/y3Gdfo1866ppyd47mg62NoiIyffSWJ4tUq1b2LZbkuiuM5UU8r31zxoza6gGqrCPWgyhUNYUM4gZrxX+IppYjtlL0ydR0ezunzmQhmZtYyBIda5Zace6hOOcVi7QJBCP/yfO/qzv2scGikX1BHbyyVcKiZabcfan/yho1Vqwuq3xrrNZgqGUX3UnnI6/UDN0+DVvpuxJ+G9VI3M3+gfrh68KrLGT/5iJLoTKG1pY0f99Ov9siKy4ii7r2E7R07YQ=
    - secure: >-
        VF4ODVXYpTZcFQG1l7dv8xT8FCEiSpewrnVe2BrbY6btg1KjSu3SXvwOtVoIRdb5K2HOmmeFGoxbI3biiCzafNoPdZDBXWsmjSfasrq9/60z1IAnD1xYo6Oe8zW5WgBoq4tmuAFcE0yz5ziyLihdSMX8ubU5MP0iF0hHkDbcyKQi1TWvacPjytiU9EyvmPSo4ga4DEHnILcjBwHLopX/iZSVeT0w84ifLyrkTofCkmRScbXwgH4dQ+JutTdwR+t2gJ4RE1iUIdMIWaOHhUwEY6Yr3qqQoSKYYMFASuRM5VXapCiTiEEug0c+YRQnzKTO1aGmfFusF6du30YxZLDMqqsErxhuIE5cDF/cAhwfhioVSmgX4HuPJy5nkr3VQQ/1mSvAHQ+uSYFK+TlFSK5zN3/w8xiaKVUsgVUHe73bj7xs+KnHSwcXJKl02K4l7HPUHiMbjhhGfdnj5uWfGQ1x50oXMGZYtapWhjwxaTS1Km6zEcm5XoR0JjTDkUrhIm//WwmZ+Tu6ejY5nKrZox0g6F55CjTdeTM0iUki3mutb/M7ebWD4JdSqA1qM/9xKQ4eqznUcM15Px3hskXNoDMx6jmyCn3CcFI5UgAMCJ4rHbw3qYW2yTsmorNncOhSeVHbGxJHpy/q6+esgohCeZGLSZcZt2UknfchrjIKDng/4rw=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
