sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        TfVBuQuNthIDviU0Zn8oXjYOZ2knPw0FatCoshiOzg1vSZCMiz4zqHxd2lY9JblUr2lboSdTgm3ks++cVYXZQgA70nc3eSMtj5mBCA9h91O9IdLeFrBtZJW7+irHCgG+Bkvry2ABWI2ZBmbeMZU8sYk0acH6Qc4yW+vfesPdWlMg3HVnhCz3YW+UMOMVA7PfJZgN6ErOUJlIWGzl0u2ftngzm+d1Lee1k7RCfn1hAyQDC0Zc6R2Sts1NOnirdiUU5sZtOi5hrGSq/cMHwXtPH7XyNwU+O/RLwztDY7vtCp61Tca5fHVPK+D7AJLqmgsQGKjhpvJU3V1aNFM0OwDkXsYFwPCV5hz1xBzlauFOvO+tLXmw0WzPQD8cNGOAaK6fL5f8iuo4RIb4RVbZepSb7vpT4jUtqi9Mem2i/hg0PiQTmMd1s63ux92SllRgAniUPos4RxSFFlJbkmm9wmvA28a0oc9WVLfeup6pF1qyTtm2Q1gCyxgZWkfnpwAR4biS1u/1U9jhDLHvpZzaDjLj02Hb+SkyKd6AdYV/gBmuDdPl4VG0P/+ig/joMrua27smI5JdA5P4l2Mul5MhDDjdFm40gd1xS7gcYi2Yx1v0R4g4Edn9d826S+HDC+zT3urg0Iam7oAhIvi3dtUxIjwKMIomF0bQvnrwJQ9gyu939zw=
    - secure: >-
        XF6Zz14G6syjepu1w+YezUQ0zL4e8Ie1vGWsUZubHfuxcvpL8RbZeR2AJWtwDTSl8cazh4IQ/J8WozzzuNiqhUjWl5TFaA/WpAhUQrA2Qa3FnTXT2SBmtzAClzBbu+DRz2pIyREpfxc6DxLYiObUkgm+pwxCYSwb23hXvwDFUp+JPN66KuhSrHF0A1wJgjf512J7IA4VAL1CoFOXJ+d3pBLjg3la3HTrRbqf80raeIrpk933uHskBjJ1UiCePiKNwbsfl+u9U4Cu8Uqx2GV5oEJALbdQW8EO2p+njtrLca4w68yM3ENWj6r/HmBaVcEF3xz6Llugh19ZtEKY7GU3xO5//lg85JJE8q6wc+zKRkQr7cEKK3J/ujhz3gLCy2fS1U2CPRie4NayD6ge8TE0EcvmGlDzg2IFydkKmA5HvjHF4LUV57B/vIQFsqwUgt1AblDBZvZo/NJGiCxo/NAo0Rc9+hxIq5kxJRegMTkpLQVgYbn39acV7f2ScHWjwe5YDaYHlDwdL4D4v0x1XtMFBpLAGWJLmpX7RfoIYR1YqzbNtOydCaStKMaj+UFQQTQzXCrIqyBNzNHlCh5k/zCIsGNdLYNRF7QV5dgu/hEE5jHXUO0aP8hsWiZ4NO9BPmSjQwg50/B1hzRGZ+ghEWKvmT3NA1laQLNlGf9hpgoI6pA=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
